### ISSUE TITLE
timezone not working

### ISSUE THREAD

**Issue by changchichung** [setiseta/docker-librenms#31]
thanks for the wonderful tool ,but I have a problem about setting timezone
I modify the docker-compose.yml to fit my timezone (Asia/Taipei)
here is the docker-compose.yml

```
version: '3'
  
services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=librenms
      - MYSQL_DATABASE=librenms
    restart: always

  librenms:                                                                                                                                                                            
    build: .
    image: seti/librenms
    container_name: librenms
    hostname: librenms
    volumes:
      - ./data:/data
    ports:
      - 8002:80
      - 514:514/tcp
      - 514:514/udp
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=librenms
      - TZ="Asia/Taipei"
      - POLLER=24
      - SERVICES_ENABLED=1
      - UPDATE_CHANNEL=master
      - SYSLOG_ENABLED=1
    restart: always
```

But I foun the time on webpage is still UTC , not 'Asia/Taipei'
is there other way to change librenms timezone ?

**Comment by setiseta** [comment]
thank you for posting the defect.
commit 26273d3 should fix it.
just wait on the new build on the docker hub, repull and retry.
a feedback would be great.

**Comment by setiseta** [comment]
it seems there is something not working on the upstream image.
i've posted an issue there hopefully i get soon the information how to fix it.

**Comment by setiseta** [comment]
The little but wrong was the "in TZ environment.
That was also wrong in examples.
I've updated the examples and documentation in commit bba2b48.

A feedback would be nice.

**Comment by changchichung** [comment]
thanks , but still wrong timestamps in event
I do a git pull and modify TZ to "Asia/Taipei"

```
version: '3'
  
services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=librenms
      - MYSQL_DATABASE=librenms
    restart: always

  librenms:
    build: .
    image: seti/librenms
    container_name: librenms
    hostname: librenms
    volumes:
      - ./data:/data
    ports:
      - 8002:80                                                                                                                                                                 
      - 514:514/tcp
      - 514:514/udp
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=librenms
      - TZ="Asia/Taipei"
      - POLLER=24
      - SERVICES_ENABLED=1
      - UPDATE_CHANNEL=master
      - SYSLOG_ENABLED=1
    restart: always

after rebuild the container , I stop snmpd service of one  devices and looks like the timestamps of rrd graph is corrent but the event time is still wrong timezone

can you please confirm that ? or it`s just my problem ?

**Comment by changchichung** [comment]
and I try to map a local file named timezone to /etc/timezone (this file always UTC , not my config Asia/Taipei) , and then I can  not login , there`s only blank page :<

**Comment by setiseta** [comment]
what i've seen is that the event log ist utc. but the rrd graphs are correct on my side.
but i've figured out, that the database timezone is by default UTC.
So you need to set the TZ environment also on the database

you shouldn't mount the /etc/timezone, cause it will be set via the TZ environment variable.
after pulling and starting with the newest image you can check if the date in the librenms container is the same as on your host:
```
user@host /path/to/librenms # date
Thu Oct  4 22:46:00 CEST 2018
user@host /path/to/librenms # /pool/container/librenmsnew # docker-compose exec librenms date
Fri Oct  5 04:46:09 CST 2018
user@host /path/to/librenms # /pool/container/librenmsnew # docker-compose exec mysql date
Fri Oct  5 04:46:14 CST 2018
```
they should all match, (not in my case cause host is CEST)

if this works for you, I will update the document & readme

**Comment by changchichung** [comment]
dunno why , I have to delete the whole folder and go a fresh new git clone , then I modify the timezone in docker-compose.yml
```
version: '3'
  
services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=librenms
      - MYSQL_DATABASE=librenms
    restart: always

  librenms:
    build: .
    image: seti/librenms
    container_name: librenms
    hostname: librenms
    volumes:
      - ./data:/data
    ports:
      - 8002:80
      - 514:514/tcp
      - 514:514/udp
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=librenms
      - TZ=Asia/Taipei
      - POLLER=24
      - SERVICES_ENABLED=1
      - UPDATE_CHANNEL=master
      - SYSLOG_ENABLED=1
    restart: always                                         
```
and 50-server.cnf
```
[mysqld]
innodb_file_per_table=1
sql-mode=""
lower_case_table_names=0
default-time-zone = '+08:00' 
```
and everything works like a charm , thanks for your help !

**Comment by setiseta** [comment]
Thanks for the feedback.
Documentation an d docker-compose.yml files are now updated with commit  2c4b288
